language: go

go:
- 1.9

before_install:
- echo " >>> downloading dep"
- go get -u github.com/golang/dep/cmd/dep

install:
- echo " >>> downloading dependencies"
- dep ensure
- dep status

before_script:
- echo " >>> preparing build informations"
- PROJECT_NAME=$(echo ${TRAVIS_REPO_SLUG} | cut -d "/" -f 2)

script:
- echo " >>> Building ${PROJECT_NAME}"
- go test -race -covermode=atomic ./...

after_success:
- echo " >>> upload codecoverage"
- bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}